CREATE TABLE groups (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_name TEXT NOT NULL,
  subgroup_name TEXT NOT NULL,
  description TEXT NOT NULL,
  triangle_a TEXT NOT NULL,
  triangle_b TEXT NOT NULL,
  linear_a TEXT NOT NULL,
  linear_b TEXT NOT NULL
)