CREATE TABLE scents (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  scent_name TEXT NOT NULL,
  groups_id INTEGER REFERENCES groups(id) ON DELETE CASCADE,
  note TEXT,
  distributor TEXT,
  manufacturer TEXT,
  type TEXT NOT NULL,
  origin_country TEXT,
  extra_origin_information TEXT,
  odor_description TEXT,
  link TEXT NOT NULL,
  weight TEXT,
  cost TEXT,
  description TEXT
)